version: "3.9"
services:
  db:
    image: postgres:14.6-bullseye
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
