databases:
  - name: gym-database
    databaseName: gym_database
    user: gym_database_user

services:
  - type: web
    name: gym-api
    branch: main
    env: ruby
    rootDir: gym-api
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gym-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: web
    name: gym-app
    branch: main
    env: static
    rootDir: gym-app
    buildCommand: "./render-build.sh"
    staticPublishPath: "./gym-app/dist/"
    buildFilter:
      paths:
        - gym-app/**/*.ts
        - gym-app/**/*.tsx
      ignoredPaths:
        - gym-app/**/*.test.ts
